session_config:
  session_id: fedat_cnn_cifar_session
  use_gpu: False
  aggregator: fedavg 
  aggregator_args: None
  client_selection: fedavg
  client_selection_args:
    client_fraction: 1
  checkpoint_interval: 1000
  validation_round_interval: 1
  generate_plots: False

benchmark_config:
  skip_benchmark: True
  model_id: FedAT_CNN
  model_dir: ../models/FedAT_CNN
  model_class: FedAT_CNN
  dataset: CIFAR10_IID
  bench_minibatch_count: 500
  batch_size: 32
  learning_rate: 0.001
  timeout_duration_s: 3600

server_training_config:
  model_dir: ../models/FedAT_CNN
  validation_dataset: CIFAR10_IID
  global_model_validation_batch_size: 100
  num_training_rounds: 100

client_training_config:
  model_id: FedAT_CNN
  model_class: FedAT_CNN
  dataset: CIFAR10_IID
  epochs: 5
  batch_size: 32
  learning_rate: 0.001
  train_timeout_duration_s: 3600
  loss_function: crossentropy
  loss_function_custom: True
  optimizer: adam
  optimizer_custom: True

model_config:
  use_custom_dataloader: False
  custom_loader_args: None

  use_custom_trainer: False
  custom_trainer_args: None

  use_custom_validator: False
  custom_validator_args: None

  model_args:
    num_classes: 10 
