session_config:
  session_id: test_session
  use_gpu: True
  aggregator: fedavg
  aggregator_args: []
  client_selection: all_clients
  client_selection_args: []
  checkpoint_interval: 1
  generate_plots: True

benchmark_config:
  skip_benchmark: True
  model_id: FedAT_CNN
  model_dir: model_cache
  model_class: FedAT_CNN
  dataset: CIFAR10_IID
  batch_size: 32
  learning_rate: 0.01
  bench_minibatch_count: 5
  timeout_duration_s: 60

server_training_config:
  model_dir: model_cache
  global_model_validation_batch_size: 32
  num_training_rounds: 5
  global_timeout_duration_s: 3600

client_training_config:
  model_id: FedAT_CNN
  model_class: FedAT_CNN
  epochs: 1
  dataset: CIFAR10_IID
  batch_size: 32
  learning_rate: 0.01
  train_timeout_duration_s: 600
  loss_function: crossentropy
  loss_function_custom: False
  optimizer: sgd
  optimizer_custom: False

model_config:
  use_custom_dataloader: False
  custom_loader_args: {}
  use_custom_trainer: False
  custom_trainer_args: {}
  use_custom_validator: False
  custom_validator_args: {}
  model_args: {}
